### ISSUE TITLE
Caso de Uso 10: Registrar Aeropuerto

### ISSUE THREAD

**Issue by oscarArismendi** [oscarArismendi/travel_agency#28]
## Descripción

- [x] Permite registrar un nuevo aeropuerto en el sistema.

## Actor Principal
Administrador del Sistema
## Precondiciones

- [x] El usuario debe tener privilegios de administrador.

## Flujo Principal

- [x] 1. El administrador selecciona la opción "Registrar Aeropuerto" en el menú principal.
- [x] 2. El sistema solicita al administrador ingresar los detalles del aeropuerto: ID, nombre,ciudad, país.
- [x] 3. El administrador ingresa los detalles solicitados.
- [x] 4. El sistema valida la información ingresada.
- [x] 5. El sistema guarda el nuevo aeropuerto en la base de datos.
- [x] 6. El sistema confirma el registro exitoso del aeropuerto.

## Postcondiciones

- [x] El aeropuerto es registrado y almacenado en la base de datos.

## Excepciones

- [x] Si alguno de los campos obligatorios no es ingresado, el sistema muestra un mensaje de error.

**Comment by oscarArismendi** [comment]
@osfa25 Can you help  me doing the register of the airport?

**Comment by osfa25** [comment]
Yes, working on it.
