### ISSUE TITLE
Caso de Uso 11: Consultar Información de Aeropuerto

### ISSUE THREAD

**Issue by oscarArismendi** [oscarArismendi/travel_agency#30]
## Descripción

- [x] Permite consultar la información de un aeropuerto registrado.

## Actor Principal
Administrador del Sistema
## Precondiciones

- [x] El usuario debe tener privilegios de administrador.

## Flujo Principal

- [x] 1. El administrador selecciona la opción "Consultar Aeropuerto" en el menú principal.
- [x] 2. El sistema solicita al administrador ingresar el ID del aeropuerto.
- [x] 3. El administrador ingresa el ID del aeropuerto.
- [x] 4. El sistema busca la información del aeropuerto en la base de datos.
- [x] 5. El sistema muestra la información del aeropuerto.

## Postcondiciones

- [x] La información del aeropuerto es mostrada al administrador.

## Excepciones

- [x] Si el aeropuerto no está registrado, el sistema muestra un mensaje de error.

**Comment by osfa25** [comment]
I want to work in this one
